### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by krima95** [krima95/Mercadona#16]
- [ ] mettre les commentaires dans le code
- [x] finir la mise en page
- [ ] faire les issues docs 
- [ ] ajouter 1 ou 2 maquettes au projet
- [ ] ajouter une animation angular dans la page
- [x] ajouter un custum pipe personnalisé
- [ ] ajouter le multi langues
- [ ] ajouter un bouton vers le back end
- [x] ajouter l'affichage des prix en promotion en rouge
